version: '3.12'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
