# Generated by Django 5.0.6 on 2024-07-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
